config/routes.rb
Rails.application.routes.draw do
  get 'home', 'index', to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <span class="navbar-home">
    <%= link_to "Home", root_path %>
  </span>
  <span class="navbar-buttons">
    <%= link_to "About", about_path %>
  </span>
  <!--<span>
    This is supposed to be a navbar
  </span>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  I've been experimenting with Ruby on Rails framework and this is what I've come up with.
  Feel free to explore this site.
</p>

app/views/pages/index.html.erb
<h1>Welcome</h1>
<p>
  This is my webpage built using Ruby on Rails framework.
  <!--<ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "welcome", welcome_index_path %></li>
  </ul>-->
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>An additional welcome page</p>
<%= link_to "home", root_path %>